/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Twinkle
 */
public class SingleSubs extends javax.swing.JPanel {

    /**
     * Creates new form SingleSubs
     */
    public SingleSubs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPhoto = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lbPhoto.setText("jLabel1");
        lbPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbPhoto);
        lbPhoto.setBounds(50, 10, 100, 70);

        lbName.setText("jLabel2");
        add(lbName);
        lbName.setBounds(44, 100, 140, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbName;
    public javax.swing.JLabel lbPhoto;
    // End of variables declaration//GEN-END:variables
}
