
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Twinkle
 */
public class SingleVideoPanel extends javax.swing.JPanel {

    /**
     * Creates new form SingleVideoPanel
     */
    public SingleVideoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLectureno = new javax.swing.JLabel();
        lbDuration = new javax.swing.JLabel();
        lbThumbnail = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        btPlay = new javax.swing.JButton();
        btDownload = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        setLayout(null);

        lbLectureno.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbLectureno.setText("bb");
        add(lbLectureno);
        lbLectureno.setBounds(190, 20, 120, 20);

        lbDuration.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbDuration.setText("Duration:");
        add(lbDuration);
        lbDuration.setBounds(190, 50, 100, 20);

        lbThumbnail.setText("x");
        lbThumbnail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(lbThumbnail);
        lbThumbnail.setBounds(10, 10, 170, 140);

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbTitle.setText("jLabel1");
        add(lbTitle);
        lbTitle.setBounds(10, 160, 290, 20);

        btPlay.setBackground(new java.awt.Color(255, 255, 153));
        btPlay.setForeground(new java.awt.Color(255, 255, 255));
        btPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/play.png"))); // NOI18N
        btPlay.setBorder(null);
        btPlay.setMinimumSize(new java.awt.Dimension(250, 250));
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });
        add(btPlay);
        btPlay.setBounds(190, 120, 30, 30);

        btDownload.setBackground(new java.awt.Color(255, 255, 153));
        btDownload.setForeground(new java.awt.Color(255, 255, 255));
        btDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/download.png"))); // NOI18N
        btDownload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(btDownload);
        btDownload.setBounds(250, 120, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed
       
        
        
    }//GEN-LAST:event_btPlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btDownload;
    public javax.swing.JButton btPlay;
    public javax.swing.JLabel lbDuration;
    public javax.swing.JLabel lbLectureno;
    public javax.swing.JLabel lbThumbnail;
    public javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
